# Scanner mode + remote Qt GUI example
# Qt GUI connects to this backend over TCP.
#
# Refer to https://github.com/rtl-airband/RTLSDR-Airband/wiki
# for description of keywords and config syntax.

stats_filepath = "/tmp/rtl_airband.prom";

devices:
({
  type = "rtlsdr";
  index = 0;
  gain = 25;
  correction = 80;
  mode = "scan";
  channels:
  (
    {
      freqs = ( 121.85, 122.875, 123.1, 123.3, 125.25, 127.15, 128.3, 130.425, 130.5, 132, 132.2, 132.3, 132.65, 133, 134.5, 134.9, 138.7, 148.145, 156.375 );
      modulations = ( "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "am", "nfm", "nfm" );
      labels = ( "Räddningstjänst Flygvapnet", "KBV", "Räddningsfrekvens", "Räddningsfrekvens", "Räddningsfrekvens", "Kustbevakningen - Räddning", "Flygräddningen", "Räddningsfrekvens", "Flygvapnet", "Flygvapnet", "Kustbevakningen", "Flygvapnet", "Räddning", "Marinen- Kustbevakningen", "Flygvapnet", "Flygvapnet", "Räddningsfrekvens", "Flygräddningen", "Sjöräddningen" );
      outputs: (
        {
          type = "tcp_stream_server";
          bind_address = "0.0.0.0";
          bind_port = 9000;
          continuous = false;
        },
        {
          type = "scan_meta_tcp_server";
          bind_address = "0.0.0.0";
          bind_port = 9001;
          continuous = false;
        }
      );
    }
  );
 }
);
